pre-commit:
  commands:
    tsc:
      glob: "*.{ts,tsx,js,json}"
      run: bun tsc --noEmit
    biome:
      glob: "*.{ts,tsx,js,json}"
      run: bun biome check --error-on-warnings --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
